#!/bin/bash

REPO_FOLDER="~/Github/os-settings"

# dotfiles
mv ~/.profile ~/.profile.old
mv ~/.zprofile ~/.zprofile.old
mv ~/.vimrc ~/.vimrc.old

ln $REPO_FOLDER/dotfiles/.profile ~/.profile
ln $REPO_FOLDER/dotfiles/.zprofile ~/.zprofile
ln $REPO_FOLDER/dotfiles/.vimrc ~/.vimrc

# .config folder
mv ~/.config/alacritty ~/.config/alacritty.old
mv ~/.config/nvim ~/.config/nvim.old

ln -s $REPO_FOLDER/.config/alacritty ~/.config/alacritty
ln -s $REPO_FOLDER/.config/nvim ~/.config/nvim

# custom .bins
mv ~/.bin ~/.bin.old

ln -s $REPO_FOLDER/.bin ~/.bin
