#!/bin/bash

config=$HOME/Github/dotfiles

# Install node.js using nvm.
source /usr/share/nvm/init-nvm.sh
nvm install --lts

# Set .vimrc.
[[ ! -f "$HOME/.vimrc" ]] && mv $HOME/.vimrc $HOME/.vimrc.old
ln -s $config/dotfiles/.vimrc $HOME/.vimrc

# Set nvim config folder.
[[ -d "$HOME/.config/nvim" ]] && mv $HOME/.config/nvim $HOME/.config/nvim.old
ln -s $config/.config/nvim $HOME/.config/nvim

# Install python3 provider in virtual env.
python3 -m venv $HOME/.config/nvim/.venv
source $HOME/.config/nvim/.venv/bin/activate
pip install pynvim
deactivate

# Install vim-plug.
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

# Install all plugins.
nvim ~/.config/nvim/plugins.vim -c :source % -c :PlugInstall -c :qa! -c :checkhealth
