#!/bin/bash

sudo pacman -S neovim nvm

source ~/.zshrc

nvm install --lts

mv ~/.config/nvim ~/.config/nvim.old

ln -s ~/Github/dotfiles/.config/nvim ~/.config/nvim

python3 -m venv ~/.config/nvim/.venv

source ~/.config/nvim/.venv/bin/activate

pip install pynvim

deactivate

sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

nvim ~/.config/nvim/plugins.vim -c :source % -c :PlugInstall -c :qa! -c :checkhealth
